USE MARKET_DB;

CREATE TABLE HONGONG1 (
	TOY_ID INT, 
    TOY_NAME CHAR(4),
    AGE INT);

-- VALUES 값을 입력할때, 열 순서 및 개수가 동일해야함.
INSERT INTO HONGONG1
VALUES ( 1, '우디', 25);

SELECT *
FROM HONGONG1;

INSERT INTO HONGONG1 (TOY_ID, TOY_NAME)
VALUES (2, '버즈');

INSERT INTO HONGONG1 (TOY_NAME, AGE, TOY_ID)
VALUES('제시', 20, 3);

-- 열을 정의할때, 1부터 자동으로 증가
CREATE TABLE HONGONG2(
	TOY_ID INT AUTO_INCREMENT PRIMARY KEY,
    TOY_NAME CHAR(4),
    AGE INT);
    
SELECT *
FROM HONGONG2;

-- 자동으로 증가되는 열은 NULL로 정의
INSERT INTO HONGONG2 
VALUES(NULL, '보핍', 25);

INSERT INTO HONGONG2 
VALUES(NULL, '슬링키', 22);

INSERT INTO HONGONG2 
VALUES(NULL, '렉스', 21);

-- 숫자가 어디까지 증가되었는지 확인
SELECT LAST_INSERT_ID();

-- 100부터 시작되도록 변경
ALTER TABLE HONGONG2 AUTO_INCREMENT = 100;

INSERT INTO HONGONG2 
VALUES(NULL, '재남', 35);


CREATE TABLE HONGONG3 (
	TOY_ID INT AUTO_INCREMENT PRIMARY KEY,
    TOY_NAME CHAR(4),
    AGE INT
    );
    
    SELECT *
    FROM HONGONG3;
    
-- 시작값은 1000으로  지정
ALTER TABLE HONGONG3 AUTO_INCREMENT=1000;
    
-- 증가값은 3으로 지정
SET @@AUTO_INCREMENT_INCREMENT=3;
    
INSERT INTO HONGONG3
VALUES(NULL, '토마스', 20);
INSERT INTO HONGONG3
VALUES(NULL, '제임스', 23);
INSERT INTO HONGONG3
VALUES(NULL, '고든', 25);
    
-- 4079개의 행이 있음
SELECT COUNT(*)
FROM WORLD.CITY;

-- 테이블 구조 확인
DESC WORLD.CITY;

SELECT *
FROM WORLD.CITY
LIMIT 5;

CREATE TABLE CITY_POPUL(
CITY_NAME CHAR(35),
POPULATION int
);

SELECT *
FROM CITY_POPUL;


-- INSERT INTO ~ SELECT 구문을 사용해 해당 테이블의 데이트를 가져와서 한 번에 입력 가능
INSERT INTO CITY_POPUL
SELECT NAME, POPULATION 
FROM WORLD.CITY;

-- SEOUL을 서울로 변경
UPDATE CITY_POPUL
SET CITY_NAME = '서울'
WHERE CITY_NAME = 'SEOUL';


SELECT *
FROM CITY_POPUL
WHERE CITY_NAME = '서울';

-- NEW YORK이 뉴욕으로 바뀌고 POPULATION은 0으로 변경됨
UPDATE CITY_POPUL
SET CITY_NAME = '뉴욕', POPULATION = 0
WHERE CITY_NAME = 'NEW YORK';

SELECT *
FROM CITY_POPUL
WHERE CITY_NAME = '뉴욕'	;

-- WHERE을 사용하지 않고 UPDATE문을 실행 할 경우 테이블 전체에 적용이됨.
UPDATE CITY_POPUL
SET POPULATION = POPULATION / 10000;

SELECT *
FROM CITY_POPUL 
LIMIT 5;


-- NEW로 시작하는 단어의 행을 삭제
DELETE 
FROM CITY_POPUL
WHERE CITY_NAME 
LIKE 'NEW%';

-- NEW로 시작하는 것 중 상위 5건만 삭제
DELETE 
FROM CITY_POPUL
WHERE CITY_NAME 
LIKE 'NEW%'
LIMIT 5;


