USE MARKET_DB;

-- 가상 VIEW 만들기 --
CREATE VIEW V_MEMBER
AS
	SELECT MEM_ID, MEM_NAME, ADDR
    FROM MEMBER;
    
SELECT *
FROM V_MEMBER;

-- 조건 사용 가능 -- 
SELECT MEM_NAME, ADDR 
FROM V_MEMBER
WHERE ADDR IN( '서울', '경기');

-- 뷰 생성 --
CREATE VIEW V_VIEWTEST1
AS
	SELECT B.MEM_ID 'MEMBER ID', M.MEM_NAME AS 'MEMBER NAME',
    B.PROD_NAME "PRODUCT NAME",
	CONCAT(M.PHONE1, M.PHONE2) AS "OFFICE PHONE"
    FROM BUY B
    INNER JOIN MEMBER M
    ON B.MEM_ID = M.MEM_ID;

SELECT DISTINCT `MEMBER ID`, `MEMBER NAME` 
FROM V_VIEWTEST1;

-- 뷰 수정 --
ALTER VIEW V_VIEWTEST1
AS
	SELECT B.MEM_ID '회원 아이디', M.MEM_NAME AS '회원 이름',
    B.PROD_NAME "제품 이름",
    CONCAT(M.PHONE1, M.PHONE2) AS "연락처"
    FROM BUY B
    INNER JOIN MEMBER M
    ON B.MEM_ID = M.MEM_ID;
    

SELECT DISTINCT `회원 아이디`, `회원 이름` 
FROM V_VIEWTEST1;

-- 뷰 삭제 --
DROP VIEW V_VIEWTEST1;

CREATE OR REPLACE VIEW V_VIEWTEST2
AS
	SELECT MEM_ID, MEM_NAME, ADDR 
    FROM MEMBER;

-- 뷰의 정보 확인 --
DESCRIBE V_VIEWTEST2;

DESCRIBE MEMBER;

SHOW CREATE VIEW V_VIEWTEST2;

-- 뷰 수정 --
UPDATE V_MEMBER
SET ADDR = '부산'
WHERE MEM_ID = 'BLK';

SELECT *
FROM V_MEMBER;

-- 뷰 생성 -- 
CREATE VIEW V_HEIGHT167
AS
	SELECT * FROM MEMBER WHERE HEIGHT >= 167;
    

SELECT * 
FROM V_HEIGHT167;

-- 뷰 삭제 --
DELETE FROM V_HEIGHT167
WHERE HEIGHT < 167;

ALTER VIEW V_HEIGHT167
AS
	SELECT * FROM MEMBER WHERE HEIGHT >= 167
    WITH CHECK OPTION;
    
INSERT INTO V_HEIGHT167
VALUES('TOB', '텔레토비', 4, '영국', NULL, NULL, 140, '1995-01-01');

-- 복합 뷰 --
CREATE VIEW V_COMPLEX
AS
	SELECT B.MEM_ID, M.MEM_NAME, B.PROD_NAME, M.ADDR
    FROM BUY B
    INNER JOIN MEMBER M
    ON B.MEM_ID = M.MEM_ID;
