-- 데이터베이스 생성
CREATE DATABASE naver_db;
-- 데이터베이스 선택
USE naver_db;
-- 테이블 생성
CREATE TABLE MEMBER(
MEM_ID 		CHAR(8) NOT NULL PRIMARY KEY, 
MEM_NAME 	VARCHAR(10) NOT NULL,
MEM_NUMBER 	TINYINT NOT NULL,
ADDR 		CHAR(2) NOT NULL,
PHONE1 		CHAR(3) NULL,
PHONE2 		CHAR(8) NULL,
HEIGHT 		TINYINT UNSIGNED NULL,
DEBUT_ID	DATE NULL
);    

CREATE TABLE BUY(
NUM 		INT AUTO_INCREMENT NOT NULL PRIMARY KEY,	-- 순번(PK)
MEM_ID		CHAR(8) NOT NULL,							-- 아이디(FK)
PROD_NAME 	CHAR(6) NOT NULL,							-- 제품 이름
GROUP_NAME 	CHAR(4) NULL,								-- 분류
PRICE 		INT UNSIGNED NOT NULL,						-- 가격
AMOUNT 		SMALLINT UNSIGNED NOT NULL,					-- 수량
FOREIGN KEY(MEM_ID) REFERENCES MEMBER(MEM_ID)
);

INSERT INTO MEMBER VALUES('TWC', '트와이스', 9 , '서울', '02', '11111111', 167, '2015-10-19');
INSERT INTO MEMBER VALUES('BLK', '블랙핑크', 4 , '경남', '055', '22222222', 163, '2016-8-8');
INSERT INTO MEMBER VALUES('WMN', '여자친구', 6 , '경기', '031', '33333333', 166, '2015-1-15');     

INSERT INTO MEMBER VALUES('TWC1', NULL, 8, '경기', '031', '44444444', 180, '2025-04-14');



SELECT * 
FROM MEMBER;     

INSERT INTO BUY VALUES(NULL, 'BLK', '지갑', NULL, 30, 2);   
INSERT INTO BUY VALUES(NULL, 'BLK', '맥북프로', '디지털', 1000, 1);
-- INSERT INTO BUY VALUES(NULL, 'APN', '아이폰', '디지털', 200, 1);          

SELECT *
FROM BUY;
          

