USE NAVER_DB;

DROP TABLE IF EXISTS BUY, MEMBER; -- BUY 테이블과 MEMBER 테이블이 존재하면 제거

DROP TABLE IF EXISTS BUY; -- BUY 테이블 존재하면 제거

DROP TABLE IF EXISTS MEMBER; -- MEMBER 테이블 존재하면 제거

CREATE TABLE MEMBER(
	MEM_ID 		CHAR(8) NOT NULL PRIMARY KEY,
    MEM_NAME 	VARCHAR(10) NOT NULL,
    HEIGHT TINYINT UNSIGNED NULL
    ); 
    
DESC MEMBER;

ALTER TABLE MEMBER ADD CONSTRAINT PRIMARY KEY (MEM_ID);
ALTER TABLE MEMBER ADD COLUMN ADDR CHAR(2);

CREATE TABLE BUY(
	NUM INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    MEM_ID CHAR(8),
    PROD_NAME CHAR(6) NOT NULL
);

DESC BUY;

ALTER TABLE BUY 
ADD CONSTRAINT FOREIGN KEY(MEM_ID) 
REFERENCES MEMBER(MEM_ID);



INSERT INTO MEMBER VALUES ('BLK', '블랙핑크', 163 , '서울');
INSERT INTO BUY VALUES (NULL, 'BLK', '지갑');
INSERT INTO BUY VALUES (NULL, 'BLK', '맥북');

SELECT *
FROM MEMBER;

SELECT *
FROM BUY;

SELECT M.MEM_ID, M.MEM_NAME, B.PROD_NAME
FROM BUY B 
INNER JOIN  MEMBER M
ON B.MEM_ID = M.MEM_ID;

-- UPDATE MEMBER 
-- SET MEM_ID = 'PINK'
-- WHERE MEM_ID = 'BLK';

-- DELETE
-- FROM MEMBER
-- WHERE MEM_ID = 'BLK';

DROP TABLE IF EXISTS BUY;

CREATE TABLE BUY(
NUM			INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
MEM_ID 		CHAR(8) NOT NULL,
PROD_NAME 	CHAR(6) NOT NULL,
FOREIGN KEY(MEM_ID) REFERENCES MEMBER(MEM_ID)
);


ALTER TABLE BUY
ADD CONSTRAINT
FOREIGN KEY(MEM_ID) REFERENCES MEMBER(MEM_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

INSERT INTO BUY VALUES(NULL, 'BLK', '지갑');
INSERT INTO BUY VALUES(NULL, 'BLK', '맥북');

UPDATE MEMBER 
SET MEM_ID = 'PINK' 
WHERE MEM_ID = 'BLK';

SELECT *
FROM BUY;

SELECT M.MEM_ID, M.MEM_NAME, B.PROD_NAME
FROM BUY B 
INNER JOIN  MEMBER M
ON B.MEM_ID = M.MEM_ID;

DROP TABLE IF EXISTS BUY, MEMBER; 

CREATE TABLE MEMBER(
	MEM_ID 		CHAR(8) NOT NULL PRIMARY KEY,
    MEM_NAME 	VARCHAR(10) NOT NULL,
    HEIGHT 		TINYINT UNSIGNED NULL,
    EMAIL 		CHAR(30) NULL UNIQUE
    ); 
    
SELECT *
FROM MEMBER;
    
INSERT INTO MEMBER VALUES('BLK', '블랙핑크', 163, 'PINK@GAMIL.COM');
INSERT INTO MEMBER VALUES('TWC', '트와이스', 167, NULL);
-- INSERT INTO MEMBER VALUES('APN', '에이핑크', 164, 'PINK@GAMIL.COM');	이메일 중복 오류
    
DROP TABLE IF EXISTS MEMBER; -- MEMBER 테이블 존재하면 제거

CREATE TABLE MEMBER(
	MEM_ID 		CHAR(8) NOT NULL PRIMARY KEY,
    MEM_NAME 	VARCHAR(10) NOT NULL,
    HEIGHT 		TINYINT UNSIGNED NULL CHECK (HEIGHT >= 100),
    PHONE1 		CHAR(3) NULL
    ); 
    
INSERT INTO MEMBER VALUES('BLK', '블랙핑크', 163, NULL);
-- INSERT INTO MEMBER VALUES('TWC', '트와이스', 99, NULL);		-- 체크 제약조건에서 설정한 값의 범위를 벗어났기에 오류 발생


ALTER TABLE MEMBER
ADD CONSTRAINT
CHECK (PHONE1 IN ('02', '031', '032', '054', '054', '055', '061'));

INSERT INTO MEMBER VALUES('TWC', '트와이스', 167, '02');
-- INSERT INTO MEMBER VALUES('OMY', '오마이걸', 167, '010');		-- CHECK 제약조건 안에 있는 수를 입력하였기 때문에 오류 발생
    
SELECT *
FROM MEMBER;
    
DROP TABLE IF EXISTS MEMBER; -- MEMBER 테이블 존재하면 제거

CREATE TABLE MEMBER(
	MEM_ID 		CHAR(8) NOT NULL PRIMARY KEY,
    MEM_NAME 	VARCHAR(10) NOT NULL,
    HEIGHT 		TINYINT UNSIGNED NULL DEFAULT 160,
    PHONE1 		CHAR(3) NULL
    ); 
    
ALTER TABLE MEMBER
ALTER COLUMN PHONE1 
SET DEFAULT '02';

INSERT INTO MEMBER VALUES('RED', '레드벨벳', 161, '054');
INSERT INTO MEMBER VALUES('SPC', '우주소녀', DEFAULT, DEFAULT);

SELECT *
FROM MEMBER;
    