-- 1. 데이터베이스 생성
CREATE DATABASE MUSTHAVE;

-- 2. 데이터베이스 선택
USE MUSTHAVE;


-- 3. 테이블 생성
CREATE TABLE MEMBER(
ID VARCHAR(10) NOT NULL,  					-- 아이디
PASS VARCHAR(10) NOT NULL,					-- 비밀번호
NAME VARCHAR(30) NOT NULL,					-- 이름
REGIDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,	-- 가입 날짜
PRIMARY KEY(ID)
);


CREATE TABLE BOARD(
NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,-- 게시판번호
TITLE VARCHAR(200) NOT NULL,-- 제목
CONTENT VARCHAR(2000) NOT NULL,-- 내용
ID VARCHAR(10) NOT NULL,-- ID
POSTDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,-- 작성일자
VISITCOUNT INT-- 조회수
);

select *
from member;
